spring:
  application:
    name: dev-week
  datasource:
    url: jdbc:h2:mem:sdw2024
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update